[project]
name = "vicmat-lab2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "freesimplegui>=5.2.0.post1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "ruff>=0.15.4",
]
